### ISSUE TITLE
Using the Chatbot

### ISSUE THREAD

**Issue by cpro90** [tensorlayer/seq2seq-chatbot#12]
Hi there,

I trained the data for a few days and now the samples are returning good results to the predefined "Happy Birthday" and "Trump" requests.

Great job by you. Thanks so far.

Do you already have a small python program for using the chatbot? If I write a message, the chatbot should return a single answer.

Thanks
Chris

**Comment by pskrunner14** [comment]
You just need to load the model you've trained and only use the inference part of the script and also change the number of queries to your preference.

**Comment by tahaozturk** [comment]
I get too many errors when i load the model and only use inference part. Can you show the full code for asking questions to the saved model?
