### ISSUE TITLE
Training is taking too much time

### ISSUE THREAD

**Issue by aqeellegalinc** [tensorlayer/seq2seq-chatbot#2]
Training on CPU is taking too much time, so do you have any estimate how much time it will take? I have executed this 12 hours ago and now i am on just "Epoch[2/50] step:[600/2852] loss:5.684645 took:9.62770s". Can you please help me to boost this training.

**Comment by zsdonghao** [comment]
hi. the best way to speed up the training is GPU.

**Comment by sr229** [comment]
@aqeellegalinc use the GPU version of Tensorflow or get a better PC:tm:

**Comment by Developer404** [comment]
Use google cloud
