### ISSUE TITLE
ERROR: Unknown token. Please try again!

### ISSUE THREAD

**Issue by nidhikamath91** [tensorlayer/seq2seq-chatbot#23]
I keep getting this error every time validation is going on. and also for testing.

Could you explain me how to solve it ?

**Comment by pskrunner14** [comment]
@nidhikamath91 it means your input consists of words that are not in the vocabulary used in the model.

**Comment by nidhikamath91** [comment]
in that case shouldnt it just replace that word by unk ?

**Comment by pskrunner14** [comment]
@nidhikamath91 it's upto how you want to take the user input. You can remove the exception handler and replace oov words with `unk`.

**Comment by nidhikamath91** [comment]
@pskrunner14  Can you explain how can I do that please ?

**Comment by nidhikamath91** [comment]
@pskrunner14  I found it, Thanks :)

**Comment by pskrunner14** [comment]
@nidhikamath91 I have made the changes. Please see #24.
