### ISSUE TITLE
No module named 'tensorlayer.models.seq2seq'

### ISSUE THREAD

**Issue by geongm** [tensorlayer/seq2seq-chatbot#37]
Can someone share with me how to resolve this error? Thanks.

Traceback (most recent call last):
  File "D:\ChatBot\seq2seq-chatbot-master\main.py", line 11, in <module>
    from tensorlayer.models.seq2seq import Seq2seq
ModuleNotFoundError: No module named 'tensorlayer.models.seq2seq'

**Comment by schedges** [comment]
From what I understand, seq2seq was removed from tensorflow2.0, which is required by tensorlayer 2+, which is what is installed by default with pip (for some reason the page is not showing up now, but it was here: https://stackoverflow.com/questions/55518391/where-is-the-seq2seq-with-tensorflow-2-0 ). On that page, they say if you're using linux, you can install tensorflow-addons to get this package back. 

I'm on OS X, so my solution was to downgrade tensorlayer to 1.11.1 (instructions to do that here: https://github.com/tensorlayer/tensorlayer), and then checkout an earlier commit where tl2.0 is not required.

**Comment by geongm** [comment]
@schedges Thanks a lot. I appreciate it.

I managed to work around it. I did not revert to previous versions of tensorlayer but I download previous version of tensorlayers and just replicate the seq2seq part manually to my packages folder. Basically, just replicating the seq2seq from previous version to ver2+.

**Comment by geongm** [comment]
@schedges By the way, how was your experience training the model? How long it took you? Mine seems to be running forever...

**Comment by ArnoldLIULJ** [comment]
it takes about 4-5 epochs to generate meaningful replies. 
Seq2seq model will be added to tensorlayer2 soon in the following days. Or you can just go to https://github.com/tensorlayer/tensorlayer/tree/seq2seq for your reference

**Comment by geongm** [comment]
@ArnoldLIULJ  Thank you. Appreciate it.
