### ISSUE TITLE
Can't import data

### ISSUE THREAD

**Issue by georgexli** [tensorlayer/seq2seq-chatbot#7]
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-ffead627eb02> in <module>()
      8 
      9 ###============= prepare data
---> 10 from data.twitter import data
     11 metadata, idx_q, idx_a = data.load_data(PATH='data/twitter/')                   # Twitter
     12 # from data.cornell_corpus import data

ModuleNotFoundError: No module named 'data.twitter'

**Comment by zsdonghao** [comment]
https://github.com/tensorlayer/seq2seq-chatbot/tree/master/data

**Comment by georgexli** [comment]
sry, may I ask a silly question 
how do I import this data file by using Jupyter Notebook
Much appreciate

**Comment by JDSlimz** [comment]
Simply commenting a link to the directory fixes nothing. Your users (including myself) are getting an error generated by your code. 

```
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    from data.twitter import data
ImportError: No module named twitter
```
So is this a module that needs to be installed? 
Are you calling it improperly?
How do your users fix this?
